# loading and preprecessing the twitter data

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("twitter_training.csv")
df

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...
...,...,...,...,...
74676,9200,Nvidia,Positive,Just realized that the Windows partition of my...
74677,9200,Nvidia,Positive,Just realized that my Mac window partition is ...
74678,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74679,9200,Nvidia,Positive,Just realized between the windows partition of...
74680,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...

In [4]:
df.shape

(74681, 4)

In [6]:
df.head(20)

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...
5,2402,Borderlands,Positive,So I spent a few hours making something for fu...
6,2402,Borderlands,Positive,So I spent a couple of hours doing something f...
7,2402,Borderlands,Positive,So I spent a few hours doing something for fun...
8,2402,Borderlands,Positive,So I spent a few hours making something for fu...
9,2402,Borderlands,Positive,2010 So I spent a few hours making something f...
10,2402,Borderlands,Positive,was
11,2403,Borderlands,Neutral,"Rock-Hard La Varlope, RARE & POWERFUL, HANDSOM..."
12,2403,Borderlands,Neutral,"Rock-Hard La Varlope, RARE & POWERFUL, HANDSOM..."
13,2403,Borderlands,Neutral,"Rock-Hard La Varlope, RARE & POWERFUL, HANDSOM..."
14,2403,Borderlands,Neutral,"Rock-Hard La Vita, RARE BUT POWERFUL, HANDSOME..."
15,2403,Borderlands,Neutral,"Live Rock - Hard music La la Varlope, RARE & t..."
16,2403,Borderlands,Neutral,"I-Hard like me, RARE LONDON DE, HANDSOME 2011,..."
17,2404,Borderlands,Positive,that was the first borderlands session in a lo...
18,2404,Borderlands,Positive,this was the first Borderlands session in a lo...
19,2404,Borderlands,Positive,that was the first borderlands session in a lo...

In [11]:
df.columns = ['u_id', 'Product', 'Sentiment', 'Review']

In [12]:
df

,u_id,Product,Sentiment,Review
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...
...,...,...,...,...
74676,9200,Nvidia,Positive,Just realized that the Windows partition of my...
74677,9200,Nvidia,Positive,Just realized that my Mac window partition is ...
74678,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74679,9200,Nvidia,Positive,Just realized between the windows partition of...
74680,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...

### Making all reviews lowercase

In [13]:
df['Review'] = df['Review'].str.lower()

In [14]:
df

,u_id,Product,Sentiment,Review
0,2401,Borderlands,Positive,i am coming to the borders and i will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...
...,...,...,...,...
74676,9200,Nvidia,Positive,just realized that the windows partition of my...
74677,9200,Nvidia,Positive,just realized that my mac window partition is ...
74678,9200,Nvidia,Positive,just realized the windows partition of my mac ...
74679,9200,Nvidia,Positive,just realized between the windows partition of...
74680,9200,Nvidia,Positive,just like the windows partition of my mac is l...

### Removing urls

In [21]:
import re
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [22]:
remove_url(df['Review'][3715])

"all right. - sniffing is strange. - movement is still a tattoo of frustration. - visibility is crap. - the game is terribly inconsistent. - the game looks amazing. - they've finally fixed the steps! - decent cards: / / co / rbs1fbynhg"

# Removing handeling with string library/module

In [23]:
import string

In [25]:
symbols=string.punctuation
symbols

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [43]:
def remove_punct(text):
    for char in symbols:
        text=text.replace(char,'')
    return text

In [44]:
text = "Damnn!! so many, punctuations!.@$%"

In [45]:
remove_punct(text)

'Damnn so many punctuations'

# Handeling Emoji

In [47]:
import emoji

In [52]:
def emojiToText(text):
    return emoji.demojize(text)

In [53]:
text = "Hello 😀, let's grab some coffee ☕ and take a 🚗 to the beach! 🏖️"

In [54]:
emojiToText(text)

"Hello :grinning_face:, let's grab some coffee :hot_beverage: and take a :automobile: to the beach! :beach_with_umbrella:"

## Stemmer and Lemmatization
- Stemmer is not that accurate
- Lemmatization provides with accurate root words

In [57]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [58]:
text = "run running runs runningly"

In [59]:
stem_words(text)

'run run run runningli'

### Lemmaization  not done rn
- but basic idea is stemming is fast and bad. Lemmatiation is slow and good

# Actual Cleaning happens

In [69]:
df

,u_id,Product,Sentiment,Review
0,2401,Borderlands,Positive,i am coming to the borders and i will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...
...,...,...,...,...
74676,9200,Nvidia,Positive,just realized that the windows partition of my...
74677,9200,Nvidia,Positive,just realized that my mac window partition is ...
74678,9200,Nvidia,Positive,just realized the windows partition of my mac ...
74679,9200,Nvidia,Positive,just realized between the windows partition of...
74680,9200,Nvidia,Positive,just like the windows partition of my mac is l...

In [84]:
for i, text in enumerate(df['Review']):
    df.loc[i, 'Review'] = remove_url(text)
    df.loc[i, 'Review'] = remove_punct(df.loc[i, 'Review'])

In [88]:
df

,u_id,Product,Sentiment,Review
0,2401,Borderlands,Positive,i am coming to the borders and i will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you all
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...
...,...,...,...,...
74676,9200,Nvidia,Positive,man gearbox really needs to fix these disappoi...
74677,9200,Nvidia,Positive,man gearbox really needs to fix this disssapoi...
74678,9200,Nvidia,Positive,man bethesda really needs to fix this dissapoi...
74679,9200,Nvidia,Positive,man gearbox really needs to fix this dissapoin...
74680,9200,Nvidia,Positive,unk gearbox really time to fix this 10 drops i...